name: Build Docker Image

on:
  push:
    branches:
      - stage
      - release
      - kiledel/*
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

jobs:
  is-versioning-pr:
    runs-on: ubuntu-latest
    outputs:
      is_versioning_pr: ${{ steps.check.outputs.is_versioning_pr }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Names
        uses: ./.github/actions/set-names
        id: names
      - name: validate semver
        id: check
        uses: ./.github/actions/validate-semver
        with:
          version: ${{ steps.names.outputs.BRANCH_NAME }}

  build:
    if: ${{ needs.is-versioning-pr.outputs.is_versioning_pr == 'false' }} 
    needs:
      - is-versioning-pr
    runs-on: ubuntu-latest
    steps:
      - name: test 
        run: |
          echo "is_versioning_pr = ${{ needs.is-versioning-pr.outputs.is_versioning_pr }}"
          echo "version = ${{ needs.is-versioning-pr.outputs.version }}"
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "DATE=$(TZ='Asia/Seoul' date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Set Names
        uses: ./.github/actions/set-names
        id: names

    outputs:
      BRANCH_NAME: ${{ steps.names.outputs.BRANCH_NAME }}
      IMAGE_NAME: ${{ steps.names.outputs.IMAGE_NAME }}

  deploy-pr:
    if: ${{ needs.build.outputs.IMAGE_NAME == 'pr' }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        run: echo "DEPLOY"
