name: Build Docker Image

on:
  push:
    branches:
      - stage
      - release
      - kiledel/*
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Update NPM
        run: npm i -g npm@latest

      - name: Install NPM Packages
        run: npm ci

      - name: Build Nuxt
        run: npm run build

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64/v8

      - name: Get current date
        id: date
        run: echo "DATE=$(TZ='Asia/Seoul' date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Set Names
        uses: ./.github/actions/set-names
        id: names

    outputs:
      BRANCH_NAME: ${{ steps.names.outputs.BRANCH_NAME }}
      IMAGE_NAME: ${{ steps.names.outputs.IMAGE_NAME }}

  deploy-pr:
    if: ${{ needs.build.outputs.IMAGE_NAME == 'pr' }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        run: echo "DEPLOY"
