name: Clean Up PR

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Names
        uses: ./.github/actions/set-names
        id: names

      - name: Clean Up
        run: echo "Clean Up"
