name: update stage branch

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Names
        run: echo ${{ github.head_ref || github.ref_name }}
      # - name: Create tag
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/<tagname>',
      #         sha: context.sha
      #       })
      # - name: Merge development -> staging
      #   uses: devmasx/merge-branch@master
      #   with:
      #     type: now
      #     from_branch: develop
      #     target_branch: stage
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
